Configuration file for Nifty 50 Trading Bot
"""

# Telegram Bot Configuration
TELEGRAM_BOT_TOKEN = "6506132532:AAGjfMXlSkefR5uldDwCRhxdk7YRES5385k"
TELEGRAM_CHAT_ID = "-1003103484269"

# Trading Configuration
NIFTY_50_STOCKS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "HINDUNILVR.NS",
    "ICICIBANK.NS", "KOTAKBANK.NS", "SBIN.NS", "BHARTIARTL.NS", "ITC.NS",
    "AXISBANK.NS", "LT.NS", "ASIANPAINT.NS", "MARUTI.NS", "HCLTECH.NS",
    "SUNPHARMA.NS", "BAJFINANCE.NS", "TITAN.NS", "ULTRACEMCO.NS", "NESTLEIND.NS",
    "WIPRO.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "TECHM.NS",
    "M&M.NS", "BAJAJFINSV.NS", "TATASTEEL.NS", "COALINDIA.NS", "ADANIPORTS.NS",
    "DIVISLAB.NS", "INDUSINDBK.NS", "DRREDDY.NS", "GRASIM.NS", "CIPLA.NS",
    "EICHERMOT.NS", "JSWSTEEL.NS", "HINDALCO.NS", "HEROMOTOCO.NS", "BRITANNIA.NS",
    "TATAMOTORS.NS", "APOLLOHOSP.NS", "SBILIFE.NS", "BPCL.NS", "UPL.NS",
    "BAJAJ-AUTO.NS", "TATACONSUM.NS", "ADANIENT.NS", "HDFCLIFE.NS", "LTIM.NS"
]

# Scanning Configuration
SCAN_INTERVAL = 60
TIMEFRAME = "5m"
LOOKBACK_PERIODS = 100

# Strategy Parameters
RSI_PERIOD = 14
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
VOLUME_SPIKE_MULTIPLIER = 1.5

# Support/Resistance Configuration
SR_LOOKBACK = 50
SR_TOUCH_THRESHOLD = 0.5

# Risk Management
MIN_RISK_REWARD_RATIO = 1.5
STOP_LOSS_PERCENTAGE = 0.8
TARGET_PERCENTAGE_1 = 1.2
TARGET_PERCENTAGE_2 = 2.0

# Chart Configuration
CHART_SAVE_PATH = "/home/admin01/Stock-Ai/charts/"
CHART_STYLE = "yahoo"

# Logging Configuration
LOG_FILE = "/home/admin01/Stock-Ai/trading_bot.log"
LOG_LEVEL = "INFO"

# Performance Settings
MAX_WORKERS = 10
ENABLE_CHART_GENERATION = True

# Data Source
DATA_SOURCE = "yahoo"
CACHE_DURATION = 300
ENDOFFILE
